version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./dbdata:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
       - MYSQL_DATABASE=${DB_DATABASE}
       - MYSQL_USER=${DB_USER}
       - MYSQL_PASSWORD=${DB_PASSWORD}
 
   wordpress:
     depends_on:
     - db
     image: wordpress:php7.4-fpm-alpine
     volumes:
      
       - ./wordpress:/var/www/html
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

     ports:
      - 8080:80 
     restart: always
     environment:
       - WORDPRESS_DB_HOST=${WP_DB_HOST}
       - WORDPRESS_DB_USER=${WP_DB_USER}
       - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
       - WORDPRESS_DB_NAME=${WP_DB_NAME}
   webserver:
    depends_on:
      - wordpress  
    image: nginx:1.15.12-alpine
    restart: always
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-conf/logs:/var/log/nginx 
    ports:
      - "8000:80" 

           

